// Generated by gencpp from file assignment2_part1/last_destinationResponse.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT2_PART1_MESSAGE_LAST_DESTINATIONRESPONSE_H
#define ASSIGNMENT2_PART1_MESSAGE_LAST_DESTINATIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assignment2_part1
{
template <class ContainerAllocator>
struct last_destinationResponse_
{
  typedef last_destinationResponse_<ContainerAllocator> Type;

  last_destinationResponse_()
    : last_destination_x(0.0)
    , last_destination_y(0.0)  {
    }
  last_destinationResponse_(const ContainerAllocator& _alloc)
    : last_destination_x(0.0)
    , last_destination_y(0.0)  {
  (void)_alloc;
    }



   typedef float _last_destination_x_type;
  _last_destination_x_type last_destination_x;

   typedef float _last_destination_y_type;
  _last_destination_y_type last_destination_y;





  typedef boost::shared_ptr< ::assignment2_part1::last_destinationResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignment2_part1::last_destinationResponse_<ContainerAllocator> const> ConstPtr;

}; // struct last_destinationResponse_

typedef ::assignment2_part1::last_destinationResponse_<std::allocator<void> > last_destinationResponse;

typedef boost::shared_ptr< ::assignment2_part1::last_destinationResponse > last_destinationResponsePtr;
typedef boost::shared_ptr< ::assignment2_part1::last_destinationResponse const> last_destinationResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignment2_part1::last_destinationResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignment2_part1::last_destinationResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::assignment2_part1::last_destinationResponse_<ContainerAllocator1> & lhs, const ::assignment2_part1::last_destinationResponse_<ContainerAllocator2> & rhs)
{
  return lhs.last_destination_x == rhs.last_destination_x &&
    lhs.last_destination_y == rhs.last_destination_y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::assignment2_part1::last_destinationResponse_<ContainerAllocator1> & lhs, const ::assignment2_part1::last_destinationResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace assignment2_part1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::assignment2_part1::last_destinationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment2_part1::last_destinationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment2_part1::last_destinationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment2_part1::last_destinationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment2_part1::last_destinationResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment2_part1::last_destinationResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignment2_part1::last_destinationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6d15e47176edc2b7745ed97161ee1d5f";
  }

  static const char* value(const ::assignment2_part1::last_destinationResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6d15e47176edc2b7ULL;
  static const uint64_t static_value2 = 0x745ed97161ee1d5fULL;
};

template<class ContainerAllocator>
struct DataType< ::assignment2_part1::last_destinationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignment2_part1/last_destinationResponse";
  }

  static const char* value(const ::assignment2_part1::last_destinationResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignment2_part1::last_destinationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 last_destination_x\n"
"float32 last_destination_y\n"
"\n"
;
  }

  static const char* value(const ::assignment2_part1::last_destinationResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignment2_part1::last_destinationResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.last_destination_x);
      stream.next(m.last_destination_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct last_destinationResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignment2_part1::last_destinationResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignment2_part1::last_destinationResponse_<ContainerAllocator>& v)
  {
    s << indent << "last_destination_x: ";
    Printer<float>::stream(s, indent + "  ", v.last_destination_x);
    s << indent << "last_destination_y: ";
    Printer<float>::stream(s, indent + "  ", v.last_destination_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENT2_PART1_MESSAGE_LAST_DESTINATIONRESPONSE_H
