// Generated by gencpp from file assignment2_part1/posit.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT2_PART1_MESSAGE_POSIT_H
#define ASSIGNMENT2_PART1_MESSAGE_POSIT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assignment2_part1
{
template <class ContainerAllocator>
struct posit_
{
  typedef posit_<ContainerAllocator> Type;

  posit_()
    : x(0.0)
    , y(0.0)
    , vel_x(0.0)
    , vel_z(0.0)  {
    }
  posit_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , vel_x(0.0)
    , vel_z(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _vel_x_type;
  _vel_x_type vel_x;

   typedef float _vel_z_type;
  _vel_z_type vel_z;





  typedef boost::shared_ptr< ::assignment2_part1::posit_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignment2_part1::posit_<ContainerAllocator> const> ConstPtr;

}; // struct posit_

typedef ::assignment2_part1::posit_<std::allocator<void> > posit;

typedef boost::shared_ptr< ::assignment2_part1::posit > positPtr;
typedef boost::shared_ptr< ::assignment2_part1::posit const> positConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignment2_part1::posit_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignment2_part1::posit_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::assignment2_part1::posit_<ContainerAllocator1> & lhs, const ::assignment2_part1::posit_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.vel_x == rhs.vel_x &&
    lhs.vel_z == rhs.vel_z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::assignment2_part1::posit_<ContainerAllocator1> & lhs, const ::assignment2_part1::posit_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace assignment2_part1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::assignment2_part1::posit_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment2_part1::posit_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment2_part1::posit_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment2_part1::posit_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment2_part1::posit_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment2_part1::posit_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignment2_part1::posit_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f201243154d36d221805a8f4ef1f7843";
  }

  static const char* value(const ::assignment2_part1::posit_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf201243154d36d22ULL;
  static const uint64_t static_value2 = 0x1805a8f4ef1f7843ULL;
};

template<class ContainerAllocator>
struct DataType< ::assignment2_part1::posit_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignment2_part1/posit";
  }

  static const char* value(const ::assignment2_part1::posit_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignment2_part1::posit_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 vel_x\n"
"float32 vel_z\n"
;
  }

  static const char* value(const ::assignment2_part1::posit_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignment2_part1::posit_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.vel_x);
      stream.next(m.vel_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct posit_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignment2_part1::posit_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignment2_part1::posit_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "vel_x: ";
    Printer<float>::stream(s, indent + "  ", v.vel_x);
    s << indent << "vel_z: ";
    Printer<float>::stream(s, indent + "  ", v.vel_z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENT2_PART1_MESSAGE_POSIT_H
