(cl:defpackage assignment2_part1-srv
  (:use )
  (:export
   "LAST_DESTINATION"
   "<LAST_DESTINATION-REQUEST>"
   "LAST_DESTINATION-REQUEST"
   "<LAST_DESTINATION-RESPONSE>"
   "LAST_DESTINATION-RESPONSE"
  ))

