(cl:defpackage assignment2_part1-msg
  (:use )
  (:export
   "<PLANNINGACTION>"
   "PLANNINGACTION"
   "<PLANNINGACTIONFEEDBACK>"
   "PLANNINGACTIONFEEDBACK"
   "<PLANNINGACTIONGOAL>"
   "PLANNINGACTIONGOAL"
   "<PLANNINGACTIONRESULT>"
   "PLANNINGACTIONRESULT"
   "<PLANNINGFEEDBACK>"
   "PLANNINGFEEDBACK"
   "<PLANNINGGOAL>"
   "PLANNINGGOAL"
   "<PLANNINGRESULT>"
   "PLANNINGRESULT"
   "<POSIT>"
   "POSIT"
  ))

